### ISSUE TITLE
Unsupported remote target address on IPV6 machine

### ISSUE THREAD

**Issue by wzr1337** [joleitner/cardano-car-documents#4]
Seems to be an IPV6 issue. Can you confirm this is not happening on pure IPV4?

`cardano-car-documents-cardano-node-1   | [ecd802bc:cardano.node.DnsSubscription:Warning:105] [2022-08-15 10:18:32.72 UTC] Domain: "relays-new.cardano-testnet.iohkdev.io" Unsupported remote target address [2600:1f16:fae:3001:0:1:0:2]:3001`

se also:
https://forum.cardano.org/t/domain-relays-new-cardano-testnet-iohkdev-io-unsupported-remote-target-address-2a0532100-3-3001/99231

**Comment by joleitner** [comment]
The problem is due to the latest version of cardano-node. I have already fixed the problem yesterday and pushed it. Just run a new build with `docker-compose up --build` and the problem should be solved.
